### ISSUE TITLE
Using unexported field in query results in panic.

### ISSUE THREAD

**Issue by nodefortytwo** [shurcooL/githubv4#37]
Whilst trying to use `updatePullRequestReview` mutation I get a panic when calling `client.mutate`

I suspect that I have made a mistake with my mutation structs but the library really shouldn't panic and should instead provide information on the error

NOTE: the mutation is successfully applied

Sample code below to aid in replicating.

```
func updateReview(ctx context.Context, client *githubv4.Client, reviewID, Body string) error {
	uuid, err := uuid.NewRandom()
	if err != nil {
		return err
	}
	var mut = githubv4.String(uuid.String())

	input := githubv4.UpdatePullRequestReviewInput{
		Body:                githubv4.String(Body),
		ClientMutationID:    &mut,
		PullRequestReviewID: reviewID,
	}

	var m struct {
		updatePullRequestReview struct {
			ClientMutationID string
		} `graphql:"updatePullRequestReview(input: $input)"`
	}

	return client.Mutate(context.Background(), &m, input, nil)
}
```

Full Panic
```
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 1 [running]:
reflect.valueInterface(0x12374c0, 0xc4201d4370, 0x36, 0x1098601, 0x123ed20, 0x12374c0)
        /usr/local/Cellar/go/1.10.3/libexec/src/reflect/value.go:959 +0x1c1
reflect.Value.Interface(0x12374c0, 0xc4201d4370, 0x36, 0x12374c0, 0xc4201d4370)
        /usr/local/Cellar/go/1.10.3/libexec/src/reflect/value.go:948 +0x44
.../vendor/github.com/shurcooL/graphql/internal/jsonutil.unmarshalValue(0x123ed20, 0xc420010180, 0x123ed20, 0xc4201d4370, 0x1b8, 0xc420084480, 0x2)
       .../vendor/github.com/shurcooL/graphql/internal/jsonutil/graphql.go:307 +0xca
.../vendor/github.com/shurcooL/graphql/internal/jsonutil.(*decoder).decode(0xc420069bd0, 0xc42024a3e0, 0x16)
       .../vendor/github.com/shurcooL/graphql/internal/jsonutil/graphql.go:147 +0x45b
.../vendor/github.com/shurcooL/graphql/internal/jsonutil.(*decoder).Decode(0xc420069bd0, 0x1237ac0, 0xc4201d4370, 0xc420069bf8, 0x12375c0)
       .../vendor/github.com/shurcooL/graphql/internal/jsonutil/graphql.go:66 +0x13d
.../vendor/github.com/shurcooL/graphql/internal/jsonutil.UnmarshalGraphQL(0xc4204e2300, 0x57, 0x60, 0x1237ac0, 0xc4201d4370, 0x12a3fed, 0x10)
       .../vendor/github.com/shurcooL/graphql/internal/jsonutil/graphql.go:23 +0x12c
.../vendor/github.com/shurcooL/graphql.(*Client).do(0xc420114340, 0x12d5a80, 0xc4200a2008, 0x4e4e312d1f4d2b01, 0x1237ac0, 0xc4201d4370, 0xc42013c3c0, 0x0, 0x0)
       .../vendor/github.com/shurcooL/graphql/graphql.go:85 +0x393
.../vendor/github.com/shurcooL/graphql.(*Client).Mutate(0xc420114340, 0x12d5a80, 0xc4200a2008, 0x1237ac0, 0xc4201d4370, 0xc42013c3c0, 0xc42013c390, 0xc42013c390)
       .../vendor/github.com/shurcooL/graphql/graphql.go:43 +0x65
.../vendor/github.com/shurcooL/githubv4.(*Client).Mutate(0xc4200b0020, 0x12d5a80, 0xc4200a2008, 0x1237ac0, 0xc4201d4370, 0x1270140, 0xc42013c390, 0xc42013c3c0, 0x0, 0x0)
       .../vendor/github.com/shurcooL/githubv4/githubv4.go:55 +0xc9
main.updateReview(0x12d5a80, 0xc4200a2008, 0xc4200b0020, 0xc42001ed20, 0x28, 0x12a2613, 0x9, 0xc420014880, 0x11)
       .../github-commenter.go:101 +0x21a
main.main()
       .../github-commenter.go:39 +0x167
exit status 2
```

**Comment by dmitshur** [comment]
Thanks a lot for reporting. I suspect this issue is https://github.com/shurcooL/graphql/issues/11. I've already started a fix for it locally, I just need to finish it and push it. I'll confirm whether it fixes this issue too.

**Comment by dmitshur** [comment]
I've investigated this, and it's not the same issue as what I thought it might be.

Your struct `m` where the results of the mutation get populated contains an unexported field:

```Go
var m struct {
	updatePullRequestReview struct {
		ClientMutationID string
	} `graphql:"updatePullRequestReview(input: $input)"`
}
```

As a result, it's not possible for another package (`github.com/shurcooL/graphql/internal/jsonutil`, in this case) to use `reflect` to access `m.updatePullRequestReview.ClientMutationID` and modify its contents. I haven't handled that edge case properly, hence the panic.

You should change your code to make `updatePullRequestReview` exported, then it'll work:

```Go
var m struct {
	UpdatePullRequestReview struct {
		ClientMutationID string
	} `graphql:"updatePullRequestReview(input: $input)"`
}
```

This is a valid bug. I'll need to think how to best handle such a situation: 

1. `encoding/json` package simply skips unexported fields, and I could do that here too.
2. An alternative is to immediately return an error, which might make debugging easier (otherwise, it might be hard to understand why the value isn't being populated).

**Comment by nodefortytwo** [comment]
Hi dmitshur,

My error is so obvious in hind sight. I am happy to close this given its purely user error but if there is anything that could be done to return an error gracefully without a panic that would be amazing.

thanks so much for your quick response

Rick

**Comment by dmitshur** [comment]
If you don’t mind, I’ll reopen this issue and use it to track the fix to the panic when unexported fields are involved. Once resolved, future users won’t run into this panic either.
